//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonPicture
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Status { get; set; }
        public byte[] FileData { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    }
}
